name: Run Tests and Upload Coverage

on:
  workflow_call:

env:
  LCOV_PATH: .build/artifacts/info.lcov
  BUILD_FOLDER: .build/debug/CombineExtensionsPackageTests.xctest/Contents/MacOS/CombineExtensionsPackageTests
  PROFDATA_FOLDER: .build/debug/codecov/default.profdata

jobs:
  run-tests-and-upload-coverage:
    name: "Run Tests and Upload Coverage"
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Tests and Generate lcov File
      run: |
        swift test --enable-code-coverage
        xcrun llvm-cov report $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER
        xcrun llvm-cov export -format="lcov" $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER > $LCOV_PATH
      
    - name: Upload Coverage Data to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ env.LCOV_PATH }}
