name: Tests On Pull Request

on:
  pull_request:
    branches: [ dev ]

jobs:
  xcode-tests:
    name: "Tests"
    runs-on: macos-12
    
    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 13"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (12.9-inch) (5th generation)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set xCode 13.4
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'

    - name: Run Tests
      run: swift test
      
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
