name: Tests On Push

on:
  push:
    branches: [ dev ]

jobs:
  run-tests-and-upload-coverage:
    uses: dsk1306/combineExtensions/.github/workflows/run-tests-and-upload-coverage.yml@codecov
    secrets: inherit
