name: Tests On Pull Request

on:
  pull_request:
    branches: [ dev ]

jobs:
  xcode-tests:
    name: "Tests"
    runs-on: macos-11
    
    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 12"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (9.7-inch)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set xCode 13.0
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: test
        spm-package: /
        scheme: CombineExtensions
        sdk: ${{ matrix.sdk }}
        destination: "${{ matrix.destination }}"
        enable-code-coverage: true
        use-xcpretty: true
    
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v2
