name: Tests On Push

on:
  push:
    branches: [ dev ]

jobs:
  xcode-tests:
    name: "Tests"
    runs-on: macos-12
    
    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 13"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (12.9-inch) (5th generation)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set xCode 13.3.1
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.3.1'

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: test
        workspace: .swiftpm/xcode/package.xcworkspace
        scheme: CombineExtensions
        sdk: ${{ matrix.sdk }}
        destination: "${{ matrix.destination }}"
        enable-code-coverage: true
        use-xcpretty: true
        resultBundlePath: testResults.xcresult
    
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v3
      with:
        xcode: true
        xcode_archive_path: testResults.xcresult
